name: intro-ml-ws
channels:
- defaults
- conda-forge
- districtdatalabs
dependencies:
- python=3.7
- feather-format=0.4.0
- jupyter=1.0.0
- matplotlib=3.1.1
- numpy=1.17.4
- pandas=0.25.3
- pyarrow=0.13.0
- pyyaml=5.1.2
- scikit-learn=0.24.1
- scikit-plot=0.3.7
- seaborn=0.11.1
- tqdm=4.41.1
- unidecode=1.1.1
- scipy=1.5.2
- yellowbrick=1.3
- nbdime=2.1.0
- pip
- pip:
  - ipython==7.10.1
  - dexplot==0.1.4
